org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
minecraft_version=1.20.1
forge_version=47.4.20
mod_id=gtohjs
mod_name=GTO HJS
mod_version=gtohjs-dev1-for-gtocore-0.6.0-dev11-fix9
mod_loader_version=1.0.0-dev11-fix9
mod_group_id=com.gtohjs
mod_authors=Futureism, Codex
mod_license=LGPL-3.0-only
