// Generated by GTOHJS Recipe Editor at 2026-09-12 21:25:10
// Target machine: gtceu:lv_extractor
// Recipe type: gtceu:extractor
// Recipe id: stem_cells
// Copy this complete class to src/main/java/com/gtohjs/recipes before rebuilding.

package com.gtohjs.recipes;

import com.gtohjs.methods.GTRecipeSource;
import com.gtohjs.methods.RecipeSourceSupport;
import com.gtolib.api.recipe.RecipeBuilder;
import com.gtolib.api.recipe.RecipeType;
import net.minecraft.resources.ResourceLocation;

/** Generated method-mode GT recipe. RecipeBuilder.save() is injected by the CoreMod. */
public final class GeneratedStemCellsRecipe73_74_65_6d_5f_63_65_6c_6c_73_ implements GTRecipeSource {
    private static final ResourceLocation RAW_ID = new ResourceLocation("gtohjs", "stem_cells");
    private RecipeBuilder configuredBuilder;
    private com.gregtechceu.gtceu.api.recipe.GTRecipeDefinition accepted;
    private int normalizedDuration;

    public GeneratedStemCellsRecipe73_74_65_6d_5f_63_65_6c_6c_73_() {}

    @Override public ResourceLocation rawId() { return RAW_ID; }
    @Override public RecipeType recipeType() { return RecipeSourceSupport.recipeType("gtceu:extractor"); }

    @Override public void configure(RecipeBuilder builder) {
        builder.inputItems(RecipeSourceSupport.itemStack("minecraft:wheat", 1, ""));
        builder.outputItems(RecipeSourceSupport.itemStack("gtceu:stem_cells", 1, ""));
        builder.EUt(30720L)
                .duration(100);
        configuredBuilder = builder;
        var raw = builder.buildRawRecipe();
        if (raw.eut != 30720L || raw.duration != 100) throw new IllegalStateException("Generated builder mismatch");
    }

    @Override public void accept(com.gregtechceu.gtceu.api.recipe.GTRecipeDefinition definition, int index) {
        if (index != 0 || configuredBuilder == null) throw new IllegalStateException("Generated save order mismatch");
        normalizedDuration = configuredBuilder.buildRawRecipe().duration;
        configuredBuilder = null;
        accepted = definition;
        validateFinalized();
    }

    @Override public void validateFinalized() {
        if (accepted == null) throw new IllegalStateException("Generated recipe was not saved");
        RecipeSourceSupport.validateGeneratedGT(accepted, normalizedDuration,
                new net.minecraft.world.item.ItemStack[]{RecipeSourceSupport.itemStack("minecraft:wheat", 1, "")},
                new net.minecraft.world.item.ItemStack[]{RecipeSourceSupport.itemStack("gtceu:stem_cells", 1, "")},
                new net.minecraftforge.fluids.FluidStack[]{}, new net.minecraftforge.fluids.FluidStack[]{},
                30720L, 0, 0, 0L);
    }
}
