// Generated by GTOHJS Recipe Editor at 2026-09-12 23:58:55
// Target machine: minecraft:crafting_table
// Recipe type: minecraft:crafting
// Recipe id: reactor_core
// Copy this complete class to src/main/java/com/gtohjs/recipes before rebuilding.

package com.gtohjs.recipes;

import com.gregtechceu.gtceu.data.recipe.VanillaRecipeHelper;
import com.gtohjs.methods.CraftingRecipeSource;
import com.gtohjs.methods.RecipeSourceSupport;
import java.util.Collection;
import java.util.List;
import net.minecraft.resources.ResourceLocation;

/** Generated method-mode shaped crafting recipe. */
public final class GeneratedReactorCoreRecipe72_65_61_63_74_6f_72_5f_63_6f_72_65_ implements CraftingRecipeSource {
    private static final ResourceLocation RAW_ID = ResourceLocation.fromNamespaceAndPath("gtohjs", "reactor_core");

    public GeneratedReactorCoreRecipe72_65_61_63_74_6f_72_5f_63_6f_72_65_() {}

    @Override public Collection<ResourceLocation> rawIds() { return List.of(RAW_ID); }

    @Override public void register() {
        RecipeSourceSupport.rememberCrafting(RAW_ID,
                RecipeSourceSupport.itemStack("gtocore:reactor_core", 1, ""),
                new String[]{"ABA", "BCB", "ABA"},
                'A', RecipeSourceSupport.itemStack("ad_astra:steel_plate", 1, ""),
                'B', RecipeSourceSupport.itemStack("gtceu:gold_plate", 1, ""),
                'C', RecipeSourceSupport.itemStack("gtocore:pulsating_alloy_block", 1, ""));
        VanillaRecipeHelper.addShapedRecipe(
                RAW_ID,
                RecipeSourceSupport.itemStack("gtocore:reactor_core", 1, ""),
                "ABA",
                "BCB",
                "ABA",
                'A', RecipeSourceSupport.itemStack("ad_astra:steel_plate", 1, ""),
                'B', RecipeSourceSupport.itemStack("gtceu:gold_plate", 1, ""),
                'C', RecipeSourceSupport.itemStack("gtocore:pulsating_alloy_block", 1, ""));
    }
}
