package com.gtohjs.methods

import net.minecraft.resources.ResourceLocation
import net.minecraftforge.fml.loading.FMLPaths
import java.io.IOException
import java.nio.charset.StandardCharsets
import java.nio.file.AtomicMoveNotSupportedException
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.StandardCopyOption
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter

/** Export only: compiled providers are manually included and rebuilt. */
object RecipeDraftWriter {
    private val commentTime = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")

    @JvmStatic
    @Throws(IOException::class)
    fun write(machineId: ResourceLocation, recipeTypeId: ResourceLocation, recipeId: String,
              className: String, source: String): Path {
        if (!className.matches(Regex("[A-Za-z_$][A-Za-z0-9_$]*"))) {
            throw IOException("Invalid generated Java class name: $className")
        }
        val gameDirectory = FMLPaths.GAMEDIR.get().toAbsolutePath().normalize()
        val outputDirectory = gameDirectory.resolve("gtohjs").resolve("recipes").normalize()
        if (!outputDirectory.startsWith(gameDirectory)) throw IOException("Recipe directory escaped game directory")
        Files.createDirectories(outputDirectory)
        val target = outputDirectory.resolve("$className.java").normalize()
        if (target.parent != outputDirectory) throw IOException("Invalid recipe draft file name")
        if (Files.exists(target)) throw IOException("Generated recipe class already exists: ${target.fileName}")
        val document = "// Generated by GTOHJS Recipe Editor at ${commentTime.format(LocalDateTime.now())}\n" +
            "// Target machine: $machineId\n// Recipe type: $recipeTypeId\n// Recipe id: $recipeId\n" +
            "// Copy this complete class to src/main/java/com/gtohjs/recipes before rebuilding.\n\n" +
            source.trim { Character.isWhitespace(it) } + "\n"
        val temporary = Files.createTempFile(outputDirectory, ".gtohjs-recipe-", ".tmp")
        try {
            Files.writeString(temporary, document, StandardCharsets.UTF_8)
            try { Files.move(temporary, target, StandardCopyOption.ATOMIC_MOVE) }
            catch (_: AtomicMoveNotSupportedException) { Files.move(temporary, target) }
        } finally { Files.deleteIfExists(temporary) }
        ModLog.info("Generated complete recipe source {}; machine={}, recipeType={}, recipeId={}",
            target, machineId, recipeTypeId, recipeId)
        return target
    }
}
