package com.gtohjs.methods

import net.minecraft.resources.ResourceLocation
import net.minecraftforge.fml.loading.FMLPaths
import java.io.IOException
import java.nio.charset.StandardCharsets
import java.nio.file.AtomicMoveNotSupportedException
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.StandardCopyOption
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter
import java.util.Locale
import java.util.UUID

/** Preserves the existing structure export format and Java record accessors. */
object StructureDraftWriter {
    private val fileTime = DateTimeFormatter.ofPattern("yyyyMMdd-HHmmss-SSS")
    private val commentTime = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")

    @JvmRecord
    data class DraftIdentity(val machineId: ResourceLocation, val fileStem: String,
                             val className: String, val createdAt: LocalDateTime)

    @JvmStatic
    fun createIdentity(machineId: ResourceLocation): DraftIdentity {
        val now = LocalDateTime.now()
        val suffix = UUID.randomUUID().toString().substring(0, 8)
        val stem = sanitize(machineId.toString()) + "__" + fileTime.format(now) + "-" + suffix
        return DraftIdentity(machineId, stem, "GtohjsStructureDraft_" + javaIdentifier(stem), now)
    }

    @JvmStatic
    @Throws(IOException::class)
    fun write(identity: DraftIdentity, minX: Int, minY: Int, minZ: Int,
              maxX: Int, maxY: Int, maxZ: Int, placeholderBlock: ResourceLocation,
              blockMapping: String, source: String): Path {
        val gameDirectory = FMLPaths.GAMEDIR.get().toAbsolutePath().normalize()
        val outputDirectory = gameDirectory.resolve("gtohjs").resolve("structures").normalize()
        if (!outputDirectory.startsWith(gameDirectory)) throw IOException("Structure directory escaped game directory")
        Files.createDirectories(outputDirectory)
        val target = outputDirectory.resolve(identity.className + ".java").normalize()
        if (target.parent != outputDirectory) throw IOException("Invalid structure draft file name")
        val document = "// Generated by GTOHJS Multiblock Structure Generator at ${commentTime.format(identity.createdAt)}\n" +
            "// Target machine: ${identity.machineId}\n" +
            "// Bounds: [$minX, $minY, $minZ] -> [$maxX, $maxY, $maxZ]\n" +
            "// Size: ${maxX - minX + 1} x ${maxY - minY + 1} x ${maxZ - minZ + 1}\n" +
            "// Controller placeholder: $placeholderBlock\n" +
            "// Air positions are emitted as spaces and matched by Predicates.any().\n" +
            "// Block mapping:\n$blockMapping\n" + source.trim { Character.isWhitespace(it) } + "\n"
        val temporary = Files.createTempFile(outputDirectory, ".gtohjs-structure-", ".tmp")
        try {
            Files.writeString(temporary, document, StandardCharsets.UTF_8)
            try { Files.move(temporary, target, StandardCopyOption.ATOMIC_MOVE) }
            catch (_: AtomicMoveNotSupportedException) { Files.move(temporary, target) }
        } finally { Files.deleteIfExists(temporary) }
        ModLog.info("Generated structure source draft {}; machine={}, placeholder={}, size={}x{}x{}",
            target, identity.machineId, placeholderBlock, maxX - minX + 1, maxY - minY + 1, maxZ - minZ + 1)
        return target
    }

    private fun javaIdentifier(value: String): String = buildString(value.length + 1) {
        for ((index, character) in value.withIndex()) {
            if (index == 0 && !Character.isJavaIdentifierStart(character)) append('_')
            append(if (Character.isJavaIdentifierPart(character)) character else '_')
        }
    }

    @JvmStatic
    fun sanitize(value: String): String = value.lowercase(Locale.ROOT)
        .replace(Regex("[^a-z0-9._-]+"), "_").trim('.').ifEmpty { "structure" }
}
